env.SAST_GIT_URL="https://github.com/efsavage/hello-world-war.git"
env.BUILD_GIT_URL="https://github.com/efsavage/hello-world-war.git"
env.FUNCTIONAL_WEB_GIT_URL="https://github.com/harishpallapu/webtest.git"
env.FUNCTIONAL_MOBILE_GIT_URL="https://github.com/harishpallapu/mobiletest.git"
env.MAIL_ID="flexib08@gmail.com"
