env.SAST_GIT_URL="https://github.com/harishpallapu/SourceCode_SAST.git"
env.BUILD_GIT_URL="https://github.com/harishpallapu/SourceCode_SAST.git"
env.TOMCAT_IP="http://140.238.240.203:8084/"
env.DAST_URL="http://140.238.240.203:8084/SpringMVCAnnotationShoppingCart"
env.FUNCTIONAL_WEB_GIT_URL="https://github.com/harishpallapu/webtest.git"
env.FUNCTIONAL_MOBILE_GIT_URL="https://github.com/harishpallapu/mobiletest.git"
env.JMETER_GIT_URL="https://github.com/harishpallapu/folder.git"
env.EMAIL_ID="bhaskar88.p@gmail.com"
